# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

target 'airbnbcalendar' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for airbnbcalendar

  target 'airbnbcalendarTests' do
    inherit! :search_paths
    pod 'Quick'
    pod 'Nimble'
    pod 'Spry+Nimble'
    pod 'AutoEquatable'
    pod 'KIF', :configurations => ['Debug']
    pod 'KIF/IdentifierTests', :configurations => ['Debug']
  end

end
